structures:
  some_list:
    - item_1
    - item_2
    - item_3
  another_list:
    [item_1, item_2, item_3]
  some_dict:
    key_1: value_1
    key_2: value_2
    key_3: value_3
  some_key:
    some_value
  some_None: ~
  another_None: null
  some_bull: true
  another_bull: false
external_launch: false
hydra:
  run:
    dir: ./
  output_subdir: null # if hydra>=1.0.0 else ./
  job_logging: null
  hydra_logging: null
